/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.JsonApiBodyResponseErrors;
import io.swagger.model.JsonApiBodyResponseErrorsOferta;
import io.swagger.model.JsonApiBodyResponseSuccessNegocio;
import io.swagger.model.JsonApiBodyResponseSuccessOferta;
import io.swagger.model.JsonApiBodyResponseSuccessPersona;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-08-17T22:23:09.345Z")

@Api(value = "eliminar", description = "the eliminar API")
public interface EliminarApi {

    @ApiOperation(value = "Eliminar negocio", nickname = "eliminarNegociosIdnegocioDelete", notes = "Eliminar negocio por id", response = JsonApiBodyResponseSuccessNegocio.class, tags={ "servicio", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "NEGOCIO ELIMINADO", response = JsonApiBodyResponseSuccessNegocio.class),
        @ApiResponse(code = 404, message = "NEGOCIO NO ENCONTRADO", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/eliminar/negocios/{idnegocio}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<JsonApiBodyResponseSuccessNegocio> eliminarNegociosIdnegocioDelete(@ApiParam(value = "ID del negocio",required=true) @PathVariable("idnegocio") String idnegocio);


    @ApiOperation(value = "Eliminar oferta", nickname = "eliminarOfertasIdofertaDelete", notes = "Eliminar ofertas por id", response = JsonApiBodyResponseSuccessOferta.class, tags={ "servicio", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OFERTA ELIMINADA", response = JsonApiBodyResponseSuccessOferta.class),
        @ApiResponse(code = 404, message = "OFERTA NO ENCONTRADO", response = JsonApiBodyResponseErrorsOferta.class) })
    @RequestMapping(value = "/eliminar/ofertas/{idoferta}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<JsonApiBodyResponseSuccessOferta> eliminarOfertasIdofertaDelete(@ApiParam(value = "ID de la oferta",required=true) @PathVariable("idoferta") String idoferta);


    @ApiOperation(value = "Eliminar persona", nickname = "eliminarPersonasIdDelete", notes = "Eliminar persona por id", response = JsonApiBodyResponseSuccessPersona.class, tags={ "servicio", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Persona eliminada", response = JsonApiBodyResponseSuccessPersona.class),
        @ApiResponse(code = 404, message = "NO ENCONTRADO", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/eliminar/personas/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<JsonApiBodyResponseSuccessPersona> eliminarPersonasIdDelete(@ApiParam(value = "ID de la persona",required=true) @PathVariable("id") String id);

}
