package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.springframework.validation.annotation.Validated;
import javax.validation.Valid;
import javax.validation.constraints.*;

/**
 * RegistrarRequest4
 */
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-07-25T19:46:33.644Z")

@DynamoDBTable(tableName = "Personas")
public class RegistrarRequest4 {

	@JsonProperty("id")
	private String id = null;

	@JsonProperty("nombre")
	private String nombre = null;

	@JsonProperty("apellidos")
	private String apellidos = null;

	@JsonProperty("correo")
	private String correo = null;

	@JsonProperty("contrasena")
	private String contrasena = null;

	@JsonProperty("telefono")
	private String telefono = null;

	@JsonProperty("genero")
	private String genero = null;

	@JsonProperty("rol")
	private String rol = null;

	@JsonProperty("estado")
	private String estado = null;
	
	@JsonProperty("ciudad")
	private String ciudad = null;

	@JsonProperty("token")
	private String token = null;

	/**
	 * Get id
	 * 
	 * @return id
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull

	
	
	@DynamoDBHashKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public RegistrarRequest4 nombre(String nombre) {
		this.nombre = nombre;
		return this;
	}

	/**
	 * Get nombre
	 * 
	 * @return nombre
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull

	@DynamoDBAttribute
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public RegistrarRequest4 apellidos(String apellidos) {
		this.apellidos = apellidos;
		return this;
	}

	/**
	 * Get apellidos
	 * 
	 * @return apellidos
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull

	@DynamoDBAttribute
	public String getApellidos() {
		return apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public RegistrarRequest4 correo(String correo) {
		this.correo = correo;
		return this;
	}

	/**
	 * Get correo
	 * 
	 * @return correo
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull

	@DynamoDBAttribute
	public String getCorreo() {
		return correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public RegistrarRequest4 contrasena(String contrasena) {
		this.contrasena = contrasena;
		return this;
	}

	/**
	 * Get contrasena
	 * 
	 * @return contrasena
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull

	@DynamoDBAttribute
	public String getContrasena() {
		return contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public RegistrarRequest4 telefono(String telefono) {
		this.telefono = telefono;
		return this;
	}

	/**
	 * Get telefono
	 * 
	 * @return telefono
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull

	@DynamoDBAttribute
	public String getTelefono() {
		return telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public RegistrarRequest4 genero(String genero) {
		this.genero = genero;
		return this;
	}

	/**
	 * Get genero
	 * 
	 * @return genero
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull

	@DynamoDBAttribute
	public String getGenero() {
		return genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public RegistrarRequest4 rol(String rol) {
		this.rol = rol;
		return this;
	}

	/**
	 * Get rol
	 * 
	 * @return rol
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull

	@DynamoDBAttribute
	public String getRol() {
		return rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public RegistrarRequest4 estado(String estado) {
		this.estado = estado;
		return this;
	}

	/**
	 * Get estado
	 * 
	 * @return estado
	 **/
	@ApiModelProperty(required = true, value = "")

	@DynamoDBAttribute
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public RegistrarRequest4 ciudad(String ciudad) {
		this.ciudad = ciudad;
		return this;
	}
	

	/**
	 * Get ciudad
	 * 
	 * @return ciudad
	 **/
	@ApiModelProperty(value = "")

	@DynamoDBAttribute
	public String getciudad() {
		return ciudad;
	}

	public void setciudad(String ciudad) {
		this.ciudad = ciudad;
	}
	
	public RegistrarRequest4 token(String token) {
		this.token = token;
		return this;
	}

	/**
	 * Get token
	 * 
	 * @return token
	 **/
	@ApiModelProperty(value = "")

	@DynamoDBAttribute
	public String gettoken() {
		return token;
	}

	public void settoken(String token) {
		this.token = token;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		RegistrarRequest4 RegistrarRequest4 = (RegistrarRequest4) o;
		return Objects.equals(this.id, RegistrarRequest4.id) && Objects.equals(this.nombre, RegistrarRequest4.nombre)
				&& Objects.equals(this.apellidos, RegistrarRequest4.apellidos)
				&& Objects.equals(this.correo, RegistrarRequest4.correo)
				&& Objects.equals(this.contrasena, RegistrarRequest4.contrasena)
				&& Objects.equals(this.telefono, RegistrarRequest4.telefono)
				&& Objects.equals(this.genero, RegistrarRequest4.genero)
				&& Objects.equals(this.rol, RegistrarRequest4.rol)
				&& Objects.equals(this.ciudad, RegistrarRequest4.ciudad)
				&& Objects.equals(this.estado, RegistrarRequest4.estado);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, nombre, apellidos, correo, contrasena, telefono, genero, rol, estado);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class RegistrarRequest4 {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
		sb.append("    apellidos: ").append(toIndentedString(apellidos)).append("\n");
		sb.append("    correo: ").append(toIndentedString(correo)).append("\n");
		sb.append("    contrasena: ").append(toIndentedString(contrasena)).append("\n");
		sb.append("    telefono: ").append(toIndentedString(telefono)).append("\n");
		sb.append("    genero: ").append(toIndentedString(genero)).append("\n");
		sb.append("    rol: ").append(toIndentedString(rol)).append("\n");
		sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
		sb.append("    ciudad: ").append(toIndentedString(ciudad)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
