package io.swagger.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Personas")
public class User {
	private String id;
	private String name;
	private String email;
	private String phone;
	private String photoName;
	
	@DynamoDBHashKey
	public String getId() {
		return id;
	}
	
	@DynamoDBAttribute
	public String getName() {
		return name;
	}
	
	@DynamoDBAttribute
	public String getEmail() {
		return email;
	}
	
	@DynamoDBAttribute
	public String getPhone() {
		return phone;
	}
	
	@DynamoDBAttribute
	public String getPhotoName() {
		return photoName;
	}

	public void setId(String id) {
		this.id = id;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public void setPhotoName(String photoName) {
		this.photoName = photoName;
	}
	
	
	
}
